# Joystick Configuration
# Use joystick_identify node to figure out which axis does what

joystick:
  - axis: "sway"
    input: 1            # num# of analog input. Find out from tuner node
    invert: true        # to invert the axis
    sensitivity: 10     # more = more sensitive. keep it > 0
    scale: "linear"     # one of linear, logarithmic
  
  - axis: "surge"
    input: 2
    invert: false
    sensitivity: 1
    scale: "linear"

  - axis: "yaw"
    input: 3
    invert: false
    sensitivity: 1
    scale: "linear"
  
  - axis: "heave"
    input: 4
    invert: false
    sensitivity: 1
    scale: "linear"
  
  - button: "A"       # Enter function of the button here
    input: 1          # input number
    invert: true