thrusters:
  # Forward left thruster
  - id: 1
    name: "front_left"
    max_duty: 1.0             # max output from -1 to 1
    angle_deg: 45             # thruster mounted 45Â° from forward axis
    position: "front"         # optional - can be 'front', 'rear', 'left', 'right'
    notes: "Used for forward-left and yaw control"
    lever_arm_distance: 0.2   # metres

  # Forward right thruster
  - id: 2
    name: "front_right"
    max_duty: 1.0
    angle_deg: -45
    position: "front"
    notes: "Used for forward-right and yaw control"
    lever_arm_distance: 0.2   # metres

  # Rear left thruster
  - id: 3
    name: "rear_left"
    max_duty: 1.0
    angle_deg: 135
    position: "rear"
    notes: "Used for backward-left and yaw control"
    lever_arm_distance: 0.2   # metres

  # Rear right thruster
  - id: 4
    name: "rear_right"
    max_duty: 1.0
    angle_deg: -135
    position: "rear"
    notes: "Used for backward-right and yaw control"
    lever_arm_distance: 0.2   # metres

  # Up thruster 1
  - id: 5
    name: "up_1"
    max_duty: 1.0          
    angle_deg: 90          
    position: "up"      
    notes: "Used for heave up"
    lever_arm_distance: 0.2   # metres

  # Up thruster 2
  - id: 6
    name: "up_2"
    max_duty: 1.0
    angle_deg: 90
    position: "up"
    notes: "Used for heave up"
    lever_arm_distance: 0.2   # metres

  # Down thruster 1
  - id: 7
    name: "down_1"
    max_duty: 1.0
    angle_deg: -90
    position: "down"
    notes: "Used for heave down"
    lever_arm_distance: 0.2   # metres

  # Down thruster 2
  - id: 8
    name: "down_2"
    max_duty: 1.0
    angle_deg: -135
    position: "down"
    notes: "Used for heave down"
    lever_arm_distance: 0.2   # metres
