# Joystick Configuration
# Use joystick_identify node to figure out which axis does what

# strafe, drive_forward, yaw, pitch, up, down

# https://docs.ros.org/en/humble/p/joy/

joystick:
  - axis: "strafe"
    input: 0
    invert: false
    sensitivity: 1
    scale: "linear"

  - axis: "drive_forward"
    input: 1            # num# of analog input. Find out from tuner node
    invert: false       # to invert the axis
    sensitivity: 1      # more = more sensitive. keep it > 0
    scale: "linear"     # one of linear, logarithmic

  - axis: "yaw"
    input: 3
    invert: false
    sensitivity: 1
    scale: "linear"
  
  - axis: "pitch"
    input: 4
    invert: false
    sensitivity: 1
    scale: "linear"

  - axis: "up"
    input: 2
    invert: false
    sensitivity: 1
    scale: "linear"

  - axis: "down"
    input: 5
    invert: false
    sensitivity: 1
    scale: "linear"
  
  - button: "A"       # Enter function of the button here
    input: 1          # input number
    invert: false

  - button: "roll_left"
    input: 9
    invert: false

  - button: "roll_right"
    input: 10
    invert: false